apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-jobmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: jobmanager
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "additional-classpath-files",
            "image": "{{ .Values.images.additional_classpath_files }}",
            "imagePullPolicy": "IfNotPresent",
            "volumeMounts": [
              {
                "name": "additional-classpath-files",
                "mountPath": "/dst"
              }
            ]
          }
        ]'
    spec:
      containers:
      - name: jobmanager
        image: {{ .Values.images.flink }}
        args:
        - jobmanager
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: ui
        env:
        - name: FLINK_CONF_DIR
          value: /etc/flink
        resources:
          limits:
            cpu: {{ .Values.resources.jobmanager.limits.cpu }}
            memory: {{ .Values.resources.jobmanager.limits.memory }}
          requests:
            cpu: {{ .Values.resources.jobmanager.requests.cpu }}
            memory: {{ .Values.resources.jobmanager.requests.memory }}
        volumeMounts:
        - name: {{ template "fullname" . }}-flink-config
          mountPath: /etc/flink
        - name: additional-classpath-files
          mountPath: /opt/flink/lib/additional-classpath-files
      volumes:
        - name: {{ template "fullname" . }}-flink-config
          configMap:
            name: {{ template "fullname" . }}-flink-config
        - name: additional-classpath-files
          emptyDir: {}
