apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-taskmanager
spec:
  replicas: {{ .Values.flink.num_taskmanagers }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: taskmanager
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "additional-classpath-files",
            "image": "{{ .Values.images.additional_classpath_files }}",
            "imagePullPolicy": "IfNotPresent",
            "volumeMounts": [
              {
                "name": "additional-classpath-files",
                "mountPath": "/dst"
              }
            ]
          }
        ]'
    spec:
      containers:
      - name: taskmanager
        image: {{ .Values.images.flink }}
        args:
        - taskmanager
        ports:
        - containerPort: 6121
          name: data
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query
        env:
        - name: FLINK_CONF_DIR
          value: /etc/flink
        resources:
          limits:
            cpu: {{ .Values.flink.num_slots_per_taskmanager }}
            memory: {{ .Values.resources.taskmanager.limits.memory }}
          requests:
            cpu: {{ .Values.flink.num_slots_per_taskmanager }}
            memory: {{ .Values.resources.taskmanager.requests.memory }}
        volumeMounts:
        - name: {{ template "fullname" . }}-flink-config
          mountPath: /etc/flink
        - name: additional-classpath-files
          mountPath: /opt/flink/lib/additional-classpath-files
      volumes:
        - name: {{ template "fullname" . }}-flink-config
          configMap:
            name: {{ template "fullname" . }}-flink-config
        - name: additional-classpath-files
          emptyDir: {}
